steps:
- name: maven:latest
  args: ['mvn', 'clean', 'install', '-D', 'skipTest']
- name: maven:latest
  args: ['mvn', 'test']
- name: node:latest
  dir: 'node'
  args: ['npm', 'install']
- name: 'gcr.io/cloud-builders/docker'
  dir: 'node'
  entrypoint: 'bash'
  args: ['-c', 'docker login --username=chretiem --password=19618dae-bb8c-45c2-9dfd-e3b0d9921b29']
- name: 'gcr.io/cloud-builders/docker'
  dir: 'node'
  entrypoint: 'bash'
  args: ['-c', 'docker build -t chretiem/repo_tpipssi:2.0.0 .']
- name: 'gcr.io/cloud-builders/docker'
  dir: 'node'
  entrypoint: 'bash'
  args: ['-c', 'docker push chretiem/repo_tpipssi:2.0.0']