image: gitlab/dind

services:
  - docker:dind

stages:
  - build
  - test
  - deploy

#before_script:
#- cd node/src
#- npm install

variables:
  MAVEN_CLI_OPTS: "--batch-mode"

build-maven:
  image: maven:latest
  script:
    - mvn $MAVEN_CLI_OPTS compile

build-docker:
  stage: build
  script:
    - cd node/
    - docker login -u chretiem -p 19618dae-bb8c-45c2-9dfd-e3b0d9921b29
    - docker build -t chretiem/repo_tpipssi:1.0.1 .
    - docker push chretiem/repo_tpipssi:1.0.1

compile-maven: 
  stage: build
  image: maven:latest
  script: 
    - echo "start maven install"
    - mvn clean install -D skipTests

test-job2:
  image: maven:latest
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
